Bigon.WebUI/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Bigon.WebUI/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            return View();
        }
    }
}

Bigon.WebUI/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Bigon.WebUI/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }
    }
}

Bigon.WebUI/Views/Shared/_breadcrumbsPartial.cshtml
<div class="breadcrumbs-section ptb-50">
    <div class="breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="breadcrumbs-inner">

                        <nav class="" role="navigation" aria-label="breadcrumbs">
                            <ul class="breadcrumb-list">
                                <li>
                                    <a asp-controller="Home" asp-action="Index" title="Back to the home page">Home</a>
                                </li>
                                <li>
                                    <span>about</span>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Bigon.WebUI/Views/Shared/_navbarPartial.cshtml
<nav>
    <ul class="middle-menu-list">
        <li>
            <a asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li>
            <a asp-controller="Shop" asp-action="Index">shop</a>
        </li>
        <li>
            <a asp-controller="Blog" asp-action="Index">blog</a>
        </li>
        <li>
            <a asp-controller="About" asp-action="index">about us</a>
        </li>
        <li>
            <a asp-controller="Contact" asp-action="Index">contact us</a>
        </li>
    </ul>
</nav>